export const UPDATE_BANNER = 'RECOMMEND_UPDATE_BANNER'
export const UPDATE_HOT_RECOMMEND = 'RECOMMEND_UPDATE_HOT_RECOMMEND'
export const UPDATE_NEW_ALBUM = 'RECOMMEND_UPDATE_NEW_ALBUM'

export const UPDATE_UP_RANKING = 'RECOMMEND_UPDATE_UP_RANKING'
export const UPDATE_NEW_RANKING = 'RECOMMEND_UPDATE_NEW_RANKING'
export const UPDATE_ORIGIN_RANKING = 'RECOMMEND_UPDATE_ORIGIN_RANKING'