export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG'

export const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX'
export const CHANGE_CURRENT_SONGLIST = 'player/CHANGE_CURRENT_SONGLIST'
export const CHANGE_CURRENT_SEQUENCE = 'player/CHANGE_CURRENT_SEQUENCE'
export const CHANGE_CURRENT_LYRIC = 'player/CHANGE_CURRENT_LYRIC'